apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "*"
  values:
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 6h